spring.application.name=goldenbooking
spring.mongodb.uri=mongodb://localhost:27017/goldenbooking

# Configuracion del puerto del servidor
server.port=8080

# Log de Spring - Nivel INFO para ver solo lo importante
logging.level.org.springframework=INFO
