spring.application.name=goldenbooking

# MongoDB - prefijo correcto
spring.mongodb.uri=mongodb://localhost:27017/goldenbooking
spring.mongodb.database=goldenbooking

# Puerto
server.port=8080

# Logs
logging.level.org.springframework=INFO
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb=DEBUG

# Mínimo 32 caracteres para HS256
miclavesecreta=goldenbooking-clave-super-secreta-2024

